name: Actions

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    name: Eslint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: npm install
        run: npm ci
      - name: npm run lint
        run: npm run lint
  tests:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: npm install
        run: npm ci
      - name: npm run test
        run: npm run test
      - name: npm run test-jest
        run: npm run test-jest
